version: '3'

services:
  server:
    build: ./server
    command: python . -s settings.yml
    volumes:
      - ./server:/app
    ports:
      - 8000:8000

#  client:
#    build: ./client
#    command: python .
#    volumes:
#      - ./client:/app
#    depends_on:
#      - server